version: '3'

services:
  flask-app:
    build:
      context: ./flask
    ports:
      - "5000:5000"
    depends_on:
      - ml-model
    networks:
      - my-network

  ml-model:
    build:
      context: ./ml-model
    ports:
      - "9696:9696"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
